// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Giraffe.QueryReader.Tests")>]
[<assembly: AssemblyProductAttribute("Giraffe.QueryReader")>]
[<assembly: AssemblyVersionAttribute("1.2.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2018-12-28T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("1.2.0")>]
[<assembly: AssemblyInformationalVersionAttribute("1.2.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","db0fa53f1140f56172536cb272e3e1fd813193b3")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Giraffe.QueryReader.Tests"
    let [<Literal>] AssemblyProduct = "Giraffe.QueryReader"
    let [<Literal>] AssemblyVersion = "1.2.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2018-12-28T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "1.2.0"
    let [<Literal>] AssemblyInformationalVersion = "1.2.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "db0fa53f1140f56172536cb272e3e1fd813193b3"
