// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Giraffe.GoodRead")>]
[<assembly: AssemblyProductAttribute("Giraffe.GoodRead")>]
[<assembly: AssemblyVersionAttribute("1.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2019-01-15T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("1.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("1.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","7c662a79d421bc4a9f1e8879296f56bfa47e0157")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Giraffe.GoodRead"
    let [<Literal>] AssemblyProduct = "Giraffe.GoodRead"
    let [<Literal>] AssemblyVersion = "1.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2019-01-15T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "1.1.0"
    let [<Literal>] AssemblyInformationalVersion = "1.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "7c662a79d421bc4a9f1e8879296f56bfa47e0157"
